spring:
  application:
    name: feign-order
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/,http://localhost:9100/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2