server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/,http://localhost:9100/eureka/
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /feign-member/**
      serviceId: feign-member
    api-b:
      path: /feign-order/**
      serviceId: feign-order