server:
  port: 8000
spring:
  application:
    ### 应用名称，用于eureka服务器上的名称，其他服务通过eureka服务器调用服务的名称
    name: member-service
eureka:
  client:
    service-url:
      ### 集群服务地址，eureka服务器的地址
      defaultZone: http://localhost:8100/eureka/,http://localhost:9100/eureka/
    ### 允许注册到eureka服务器上
    register-with-eureka: true
    ###
    fetch-registry: true
  instance:
    ### 客户端向eureka服务器发送心跳的时间间隔，单位为秒
    lease-renewal-interval-in-seconds: 1
    ### Eureka服务器在收到最后一次心跳之后等待的时间上限，单位为秒，超过则删除
    lease-expiration-duration-in-seconds: 2
